[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = true

[tasks.clean]
command = "cargo"
args = ["clean"]

[tasks.format]
install_crate = "rustfmt"
command = "cargo"
args = ["fmt"]

[tasks.clippy]
install_crate = "cargo-clippy"
command = "cargo"
args = ["clippy"]

[tasks.build]
command = "cargo"
args = ["build"]
dependencies = ["format", "clippy", "clean"]


[tasks.test]
command = "cargo"
args = ["test"]
dependencies = ["format", "clippy", "clean"]

[tasks.flow]
dependencies = [
    "build",
    "test"
]
