name: ci_pipeline

# All in one ci pipeline
#  Note that the jobs system-test_offsite_{abcd} , install-and-use-rpi_m32sd10{abcd}
#  are there four times and are almost identical. They only differ in a character
#  a,b,c,d that we use to select a runner.
#
# TODO: Safely move cargo test on amd64 to bash script
# TODO: Reduce complexity by moving functionality to bash scripts
# TODO: Smoke testing on Azure is disabled, we should check if it works out
#   with 4 runners in parallel or enable only one

on:
  push:
    branches: [ main, 'release-*' ]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  build-amd64:
    name: Build for amd64
    runs-on: Ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Enable toolchain via github action
        # https://github.com/actions-rs/toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.58.1
          override: true

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Build packages for amd64
        run: ./ci/build_scripts/build_for_amd64.sh

      - name: Upload artifacts as zip
        # https://github.com/marketplace/actions/upload-a-build-artifact
        uses: actions/upload-artifact@v3
        with:
          name: debian-packages-amd64
          path: target/debian/*.deb

#################################################################################

  install-and-use-amd64:
    name: Install artifacts on amd64
    runs-on: Ubuntu-20.04
    needs: build-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download release artifacts
        uses: actions/download-artifact@v3
        # https://github.com/marketplace/actions/download-a-build-artifact
        with:
          name: debian-packages-amd64
          path: debian-package_unpack

      - name: Install artifacts on amd64
        run: ./ci/installation_scripts/install_for_amd64.sh debian-package_unpack

      - name: Run tedge help
        run: tedge --help

#################################################################################

  cargo-test-features-amd64:
    name: Run cargo test features
    runs-on: Ubuntu-20.04
    needs: build-amd64

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Enable toolchain via github action
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.58.1
          override: true

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Compile test
        run: ./ci/integration_test/cargo_test_for_amd64.sh

        # If this command is ported to bash script, it runs tests that should be skipped.
        # The tests could fail if GitHub blocks external connections.
        # It seems like they rarely do.
      - name: Cargo test features
        uses: actions-rs/cargo@v1
        # https://github.com/marketplace/actions/rust-cargo
        with:
          command: test
          args: --verbose --features integration-test,requires-sudo -- \
            --skip sending_and_receiving_a_message

##################################################################################

  build-arm-matrix:
    name: Build for ${{ matrix.target }}
    runs-on: Ubuntu-20.04
    strategy:
      matrix:
        # Add only arm targets here as we use a custom strip binary!
        target:
          [
            aarch64-unknown-linux-gnu,
            aarch64-unknown-linux-musl,
            arm-unknown-linux-gnueabihf,
            armv7-unknown-linux-gnueabihf,
            armv7-unknown-linux-musleabihf,
          ]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Enable toolchain via github action
        # https://github.com/actions-rs/toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.58.1
          target: ${{ matrix.target }}
          override: true

      - name: Enable cache
        # https://github.com/marketplace/actions/rust-cache
        uses: Swatinem/rust-cache@v1

      - name: Build for ${{ matrix.target }}
        run: ./ci/build_scripts/build_for_arm.sh ${{ matrix.target }}

      - name: Upload debian packages as zip
        # https://github.com/marketplace/actions/upload-a-build-artifact
        uses: actions/upload-artifact@v3
        with:
          name: debian-packages-${{ matrix.target }}
          path: target/${{ matrix.target }}/debian/*.deb

      - name: Upload sawtooth publisher as zip
        # https://github.com/marketplace/actions/upload-a-build-artifact
        uses: actions/upload-artifact@v3
        with:
          name: sawtooth_publisher_${{ matrix.target }}
          path: target/${{ matrix.target }}/release/sawtooth_publisher

      - name: Upload dummy-plugin as zip
        # https://github.com/marketplace/actions/upload-a-build-artifact
        uses: actions/upload-artifact@v3
        with:
          name: tedge_dummy_plugin_${{ matrix.target }}
          path: target/${{ matrix.target }}/release/tedge_dummy_plugin

#################################################################################

  clean-up-rpi-matrix:
    strategy:
      matrix:
        rpi: [ m32sd10a, m32sd10b, m32sd10c, m32sd10d ]
    runs-on:
      - self-hosted
      - Linux
      - ARM
      - offsite_${{ matrix.rpi }}
    needs: build-arm-matrix

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Clean up ${{ matrix.rpi }}
        run: ./ci/installation_scripts/clean_up_rpi.sh
        continue-on-error: true

#################################################################################

  install-and-use-rpi-matrix:
    strategy:
      matrix:
        rpi: [ m32sd10a, m32sd10b, m32sd10c, m32sd10d ]
    runs-on:
      - self-hosted
      - Linux
      - ARM
      - offsite_${{ matrix.rpi }}
    needs: clean-up-rpi-matrix

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download release artifacts
        uses: actions/download-artifact@v3
        # https://github.com/marketplace/actions/download-a-build-artifact
        with:
          name: debian-packages-armv7-unknown-linux-gnueabihf
          path: debian-package_unpack

      - name: Download sawtooth publisher
        uses: actions/download-artifact@v3
        # https://github.com/marketplace/actions/download-a-build-artifact
        with:
          name: sawtooth_publisher_armv7-unknown-linux-gnueabihf
          path: /home/pi/examples

      - name: Download tedge_dummy_plugin
        uses: actions/download-artifact@v3
        # https://github.com/marketplace/actions/download-a-build-artifact
        with:
          name: tedge_dummy_plugin_armv7-unknown-linux-gnueabihf
          path: /home/pi/tedge_dummy_plugin

      - name: Install all
        run: ./ci/installation_scripts/install_for_arm.sh debian-package_unpack

      - name: Configure Bridge
        run: ./ci/configure_bridge.sh
        env:
          C8YPASS: ${{ secrets.SECRET_C8YPASS }}
          C8YUSERNAME: ${{ secrets.SECRET_C8YUSERNAME }}
          C8YTENANT: ${{ secrets.SECRET_C8YTENANT }}
          C8YDEVICE: ${{ matrix.rpi }}
          TEBASEDIR: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/
          EXAMPLEDIR: /home/pi/examples
          C8YURL: https://thin-edge-io.eu-latest.cumulocity.com
          IOTHUBNAME: ${{ secrets.IOTHUBNAME }}

      - name: Run smoke test for Cumulocity
        run: ./ci/ci_smoke_test_c8y.sh
        env:
          C8YPASS: ${{ secrets.SECRET_C8YPASS }}
          C8YUSERNAME: ${{ secrets.SECRET_C8YUSERNAME }}
          C8YTENANT: ${{ secrets.SECRET_C8YTENANT }}
          C8YDEVICE: ${{ matrix.rpi }}
          TEBASEDIR: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/
          EXAMPLEDIR: /home/pi/examples
          C8YURL: https://thin-edge-io.eu-latest.cumulocity.com
          IOTHUBNAME: ${{ secrets.IOTHUBNAME }}

# Run tests for Azure
# Enable this, when we have decided about how many runners we use
#
#      - name: Run Smoke Test for Azure
#        run: ./ci/ci_smoke_test_az.sh
#        env:
#          SASKEYQUEUE: ${{ secrets.SASKEYQUEUE }}
#          SASKEYIOTHUB: ${{ secrets.SASKEYIOTHUB }}
#          AZUREENDPOINT: ${{ secrets.AZUREENDPOINT }}
#          AZUREEVENTHUB: ${{ secrets.AZUREEVENTHUB }}
#          IOTHUBNAME: ${{ secrets.IOTHUBNAME }}

#################################################################################

  system-test-offsite-matrix:
    strategy:
      matrix:
        rpi: [ m32sd10a, m32sd10b, m32sd10c, m32sd10d ]
    runs-on:
      - self-hosted
      - Linux
      - ARM
      - offsite_${{ matrix.rpi }}
    needs: install-and-use-rpi-matrix

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run all Tests
        run:  bash ./ci/ci_run_all_tests.sh
        continue-on-error: true
        if: true
        env:
          C8YPASS: ${{ secrets.SECRET_C8YPASS }}
          C8YUSERNAME: ${{ secrets.SECRET_C8YUSERNAME }}
          C8YDEVICE: ${{ matrix.rpi }}
          C8YTENANT: ${{ secrets.SECRET_C8YTENANT }}
          C8YURL: https://thin-edge-io.eu-latest.cumulocity.com
          TEBASEDIR: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/
          EXAMPLEDIR: /home/pi/examples

      - name: Run all plugin tests
        run:  bash ./ci/ci_run_all_plugin_tests.sh
        continue-on-error: true
        if: true
        env:
          C8YPASS: ${{ secrets.SECRET_C8YPASS }}
          C8YUSERNAME: ${{ secrets.SECRET_C8YUSERNAME }}
          C8YDEVICE: ${{ matrix.rpi }}
          C8YTENANT: ${{ secrets.SECRET_C8YTENANT }}
          TEBASEDIR: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/
          EXAMPLEDIR: /home/pi/examples
          C8YURL: https://thin-edge-io.eu-latest.cumulocity.com

      - name: Run all sm tests
        run:  bash ./ci/ci_run_all_sm_tests.sh
        continue-on-error: true
        if: true
        env:
          C8YPASS: ${{ secrets.SECRET_C8YPASS }}
          C8YUSERNAME: ${{ secrets.SECRET_C8YUSERNAME }}
          C8YDEVICE: ${{ matrix.rpi }}
          C8YTENANT: ${{ secrets.SECRET_C8YTENANT }}
          TEBASEDIR: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/
          EXAMPLEDIR: /home/pi/examples
          C8YURL: https://thin-edge-io.eu-latest.cumulocity.com

      - name: Run all statistics tests
        run:  bash ./ci/ci_run_statistics.sh
        continue-on-error: true
        if: true
        env:
          C8YPASS: ${{ secrets.SECRET_C8YPASS }}
          C8YUSERNAME: ${{ secrets.SECRET_C8YUSERNAME }}
          C8YDEVICE: ${{ matrix.rpi }}
          C8YTENANT: ${{ secrets.SECRET_C8YTENANT }}
          C8YURL: https://thin-edge-io.eu-latest.cumulocity.com
          TEBASEDIR: /home/pi/actions-runner/_work/thin-edge.io/thin-edge.io/
          EXAMPLEDIR: /home/pi/examples

      - name: Upload results as zip
        # https://github.com/marketplace/actions/upload-a-build-artifact
        uses: actions/upload-artifact@v3
        with:
          name: results_pysys_offsite_${{ matrix.rpi }}
          path: tests/

#############################################################################

  system-test-postprocessing:
    runs-on: Ubuntu-20.04
    needs: system-test-offsite-matrix

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Trigger repo dispatch here.
    # This is here a limitation of the amount of workflows
    # that trigger each other (GitHub Bug).
    # It would be nicer to use the postprocess trigger instead

# Disabled until analytics VM is available
#
#    - name: Repository Dispatch
#      uses: peter-evans/repository-dispatch@v1
#      with:
#          token: ${{ secrets.SECRET_THEGHTOKEN  }}
#          event-type: postprocess
#          repository: abelikt/thin-edge.io_analytics

    - name: Download result a
      uses: actions/download-artifact@v3
      # https://github.com/marketplace/actions/download-a-build-artifact
      with:
        name: results_pysys_offsite_m32sd10a
        path: results/results_pysys_offsite_m32sd10a

    - name: Download result b
      uses: actions/download-artifact@v3
      # https://github.com/marketplace/actions/download-a-build-artifact
      with:
        name: results_pysys_offsite_m32sd10b
        path: results/results_pysys_offsite_m32sd10b

    - name: Download result c
      uses: actions/download-artifact@v3
      # https://github.com/marketplace/actions/download-a-build-artifact
      with:
        name: results_pysys_offsite_m32sd10c
        path: results/results_pysys_offsite_m32sd10c

    - name: Download result d
      uses: actions/download-artifact@v3
      # https://github.com/marketplace/actions/download-a-build-artifact
      with:
        name: results_pysys_offsite_m32sd10d
        path: results/results_pysys_offsite_m32sd10d

    - name: Build report
      run: ./ci/report/build.sh

    - name: Upload report as zip
      # https://github.com/marketplace/actions/upload-a-build-artifact
      uses: actions/upload-artifact@v3
      with:
        name: report_matrix_${{ github.run_number }}
        path: results/report.zip

    - name: Upload report as html
      # https://github.com/marketplace/actions/upload-a-build-artifact
      uses: actions/upload-artifact@v3
      with:
        name: system-test-report-matrix_${{ github.run_number }}
        path: results/report-matrix.htm

    - name: Run ls on analysis folder
      run: |
        ls -l ./results

    - name: Deploy to GitHub Pages
      # peaceiris/actions-gh-pages@v3
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./results
        destination_dir: results
        commit_message: Results for ci pipeline run ${{ github.run_number }}

    - name: Final Result
      # This will fail if there are errors in the reports
      run: |
        python3 ./ci/report/final_result.py ./results/all_reports.xml
