name: thinedge_ci 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
     runs-on: ${{ matrix.os}}

     strategy:
       matrix:
                          
         include:
          - os: ubuntu-latest
                                             
          - os: Raspbian32            

          - os: Ubuntu20.04  

     steps:
      - uses: actions/checkout@v2
      - name: Test and Build script 
        run:  bash  ./scripts/test_build.sh
